#server port
server:
  port: 7001

dubbo:
  application:
    name: @project.name@

spring:
  security:
    user:
      name: admin
      password: admin
  profiles:
    include: common

system:
  group:
    name: system-group

seata:
  application-id: @project.name@
  tx-service-group: @project.name@ #也用来生成nacos中的dataId
