dubbo:
  application:
    name: @project.name@
server:
  port: 7005

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 192.168.10.91:22122,192.168.10.92:22122
