#server port
server:
  port: ${random.int[1000,10000]}

#db config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/easyray?useUnicode=true&characterEncoding=utf8
    username: easyray
    password: easyray
    type: com.alibaba.druid.pool.DruidDataSource

#dubbo config
dubbo:
  application:
    name: user-service
  protocol:
    name: dubbo
  registry:
    address: zookeeper://localhost:2181

#admin config
admin:
  username: admin
  password: admin

#log
logging:
  file:
    path: .
